[package]
name = "merlen"
version = "0.1.0"
edition = "2021"

[features]
default = ["gc"]
gc = ["dumpster", "itertools"]

[dependencies]
dumpster = { optional = true, version = "0.1.2", features = ["derive"] }
itertools = { optional = true, version = "0.13.0" }
